name: check PR

on:
  pull_request:
    branches: 
      - "main" 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install