name: check PR

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Checkout
      #   run: |
      #     npm run typecheck

      - name: Build
        run: |
          npm install
